platformName=iOS
automationName=XCUITest
deviceName=iPhone 15
platformVersion=17.5
bundleId=com.saucelabs.SwagLabsMobileApp
udid=${UDID}
wdaLocalPort=8000
wdaLaunchTimeout=60000
wdaStartupRetries=4
wdaStartupRetryInterval=200000
noReset=true
fullReset=false
useNewWda=false
preventWDAAttachments=true

# API target (Phase 5)
api.baseUrl=https://automationexercise.com
api.timeout.seconds=30
